config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :lists do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lists, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @user = current_user
    @lists = @user.lists
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    if @list.save
      redirect_to list_tasks_path(@list)
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @list = List.find(params[:list_id])
    @tasks = @list.tasks
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @list = List.find(params[:list_id])
    @task.list = @list
    @task.done = false
    if @task.save
      redirect_to list_tasks_path
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to list_tasks_path
  end

  def update
    @task = Task.find(params[:id])
    if @task.done?
      @task.done = false
    else
      @task.done = true
    end
    @task.update(task_status_params)
    redirect_to list_tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:description, :done)
  end

  def task_status_params
    params.permit(:done)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<%= render 'shared/list_form' %>

app/views/lists/index.html.erb
<div class="container mt-3 text-center">
  <%= link_to "Create a new list !", new_list_path, class: "btn btn-santa add-list" %>
  <div class="lists-list row justify-content-center">
    <% @lists.each do |list| %>
      <%= link_to list_tasks_path(list) do %>
      <div class="card col-10 col-sm-6 col-md-4 col-lg-3 justify-content-around">
        <div class="card-header d-flex justify-content-between">
          <%= list.name %>
          <div class="edit">
            <%= link_to edit_list_path(list) do %>
              <i class="fas fa-pencil-alt"></i>
            <% end %>
            <%= link_to list_path(list), method: :delete do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          </div>
        </div>
        <div class="card-body">
          <ul>
            <% list.tasks.each do |task| %>
              <li><%= task.description %></li>
            <% end %>
          </ul>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>

</div>

app/views/lists/new.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name%>
  <%= f.submit %>
<% end %>

app/views/pages/home.html.erb
<div class="banner">
  <h2>Even Santa makes lists!</h2>
  <% if user_signed_in? %>
    <%= link_to "See all my lists!", lists_path, class: "btn btn-santa desktop" %>
  <% else %>
    <%= link_to "Start now!", new_user_session_path, class: "btn btn-santa desktop" %>
  <% end %>
</div>

<div class="banner-presentation mb-5">
  <h3><strong>List</strong> is your best friend to organized, planned or remember what you have to do!</h3>
  <% if user_signed_in? %>
    <%= link_to "See all my lists!", lists_path, class: "btn btn-santa mobile" %>
  <% else %>
    <%= link_to "Start now!", new_user_session_path, class: "btn btn-santa mobile" %>
  <% end %>
</div>

<div class="description container row justify-content-between mx-auto">
  <div class="card col-10 col-md-7 col-lg-3 mb-3 mx-auto">
    <%= image_tag("create.svg", class: "card-img-top") %>
    <div class="card-body">
      <h5 class="card-title text-center">Create a list</h5>
      <p class="card-text">You can create as many list as you want to organize your life!</p>
    </div>
  </div>
  <div class="card col-10 col-md-7 col-lg-3 mb-3 mx-auto">
    <%= image_tag("add.svg", class: "card-img-top") %>
    <div class="card-body">
      <h5 class="card-title text-center">Add tasks</h5>
      <p class="card-text">Each list can have tasks of your choice.</p>
    </div>
  </div>
  <div class="card col-10 col-md-7 col-lg-3 mb-3 mx-auto">
    <%= image_tag("done.svg", class: "card-img-top") %>
    <div class="card-body">
      <h5 class="card-title text-center">Just do it!</h5>
      <p class="card-text">Now you can do all tasks of your lists, and mark them as done! </p>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_list_form.html.erb
<div class="col-10 col-md-6 mt-5 container">
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name, label: "What's your list name?" %>
    <%= f.submit %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav>
  <ul class="nav-list">
    <li><%= link_to root_path do %>
      <i class="fas fa-clipboard-check fa-3x"></i></li>
    <% end %>
    <% if user_signed_in? %>
      <li><%= link_to "All lists", lists_path %></li>
      <li><%= link_to "New list!", new_list_path, class: "btn btn-new-list" %></li>
      <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to "Login", new_user_session_path %></li>
    <% end %>
  </ul>
</nav>

app/views/tasks/index.html.erb
<div class="container task-card">

  <ul class="col-12 col-sm-8 col-lg-5 p-3 mx-auto">
    <h3 class='my-5'><%= @list.name %></h3>
    <% @tasks.each do |task| %>
      <li class="d-flex list-task py-2">
        <%= link_to list_task_path(@list, task), method: :patch, class: "pr-2" do %>
          <% if task.done? %>
            <i class="far fa-check-circle"></i>
          <% else %>
            <i class="far fa-circle"></i>
          <% end %>
        <% end %>
        <p class="task-decription pr-2 m-0"><%= task.description %></p>
        <%= link_to list_task_path(@list, task), method: :delete do %>
          <i class="far fa-trash-alt"></i>
        <% end %>
      </li>
    <% end %>
    <div class="task-form mt-3">
      <%= simple_form_for([@list, @task]) do |f| %>
        <%= f.input_field :description, label: false, placeholder: "Add a new task..." %>
        <%= button_tag type: "submit" do %>
          <i class="fas fa-plus"></i>
        <% end %>
    <% end %>
    </div>
  </ul>
</div>